sudo: false

dist: trusty

addons:
  apt:
    packages:
    - make
    - texlive
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - biber

script:
  - make project

before_deploy:
  - pip install -r requirements.txt

deploy:
  provider: script
  skip_cleanup: true
  script: python deploy_to_dropbox.py
  on:
    branch: master
